# Generated by Django 5.2.3 on 2025-06-18 12:05

import django.db.models.deletion
import documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('policy', 'Policy'), ('payroll', 'Payroll'), ('leave', 'Leave Documents'), ('report', 'Reports'), ('project', 'Project Files'), ('training', 'Training'), ('announcement', 'Announcements'), ('template', 'Templates'), ('hr', 'HR Documents'), ('legal', 'Legal'), ('other', 'Other')], default='report', max_length=50)),
                ('file', models.FileField(upload_to=documents.models.upload_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.department')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
